stages:
- name: Build
  steps:
  - runScriptConfig:
      image: node:12.19
      shellScript: |-
        npm install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: matheus:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml

